services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\Monitoring\:
        resource: '../../*'

    Becklyn\Monitoring\Twig\MonitoringTwigExtension:
        $environment: '%kernel.environment%'
        $isDebug: '%kernel.debug%'

    Becklyn\Monitoring\Asset\AssetProvider:
        $assetHelper: '@?Becklyn\AssetsBundle\Helper\AssetHelper'
        $packages: '@?Symfony\Component\Asset\Packages'
